version: "3.8"
services:
  db:
    container_name: crunchivote
    image: postgres:16.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crunchivote
