version: "3.8"
services:
  db:
    container_name: crunchivote
    image: postgres:16.1-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crunchivote
  # backend:
  #   build:
  #     context: /backend/src
  #     dockerfile: Dockerfile
  #   container_name: crunchivote_api
  #   restart: always
  #   ports:
  #     - 8080:8080